Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,6 @@ name: CICD Pipeline
 on:
   push:
     branches: main
-    
 
 env:
   KUBECONFIG: ${{ secrets.KUBECONFIG }}
@@ -17,52 +16,63 @@ jobs:
 
       - name: Setup python
         uses: actions/setup-python@v2
-        with: 
+        with:
           python-version: '3.9'
-          
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          
-          
-      
-        
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Set up QEMU
+
+      - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
-      -
-        name: Set up Docker Buildx
+
+      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      -
-        name: Build and push
+
+      - name: Build and push
         uses: docker/build-push-action@v6
         with:
           push: true
           tags: himateja0206/flaskdemo:latest
-          context:
+          context: .
           file: app/Dockerfile
-  
+
   deploy:
     needs: build
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-    - name: Debug Kubernetes Configuration
-      run: |
-        echo "Validating KUBECONFIG..."
-        cat $KUBECONFIG
-        kubectl config view
-    - name: Deploy to k8s
-      run: |
-        kubectl cluster-info
-        kubectl apply -f deployment.yaml
-      env:
-        KUBECONFIG: ${{ env.KUBECONFIG }} 
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Install Minikube
+        run: |
+          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
+          chmod +x minikube
+          sudo mv minikube /usr/local/bin/
+          minikube start
+
+      - name: Debug Kubernetes Configuration
+        run: |
+          if [ -f "$KUBECONFIG" ]; then
+            echo "KUBECONFIG exists. Validating configuration..."
+            cat $KUBECONFIG
+            kubectl config view
+          else
+            echo "Error: KUBECONFIG file does not exist."
+            exit 1
+          fi
+
+      - name: Deploy to k8s
+        run: |
+          kubectl cluster-info
+          kubectl apply -f deployment.yaml
+        env:
+          KUBECONFIG: ${{ env.KUBECONFIG }}
